- hosts: localhost
  connection: local
  vars_files:
    - vars.yml

  tasks:
    - include_tasks: tasks/digitalocean.yml

    - name: Add deploy hook
      github_hooks:
        action: create
        hookurl: https://{{ item.key }}
        user: '{{ github_user }}'
        oauthkey: '{{ github_token }}'
        repo: https://api.github.com/repos/{{ github_owner }}/{{ item.value.repo }}
      with_dict: "{{ virtual_hosts }}"

- hosts: dohosts

  vars_files:
    - defaults/main.yml
    - vars.yml

  tasks:
    - include_tasks: tasks/swap.yml
    - include_tasks: tasks/software.yml
    - include_tasks: tasks/security.yml
    - include_tasks: tasks/users.yml
    - include_tasks: tasks/git.yml
    - include_tasks: tasks/apache.yml

  handlers:
    - import_tasks: handlers/site.yml
