- name: Create web directories
  file:
    path: /var/www/{{ item }}
    state: directory
    owner: www-data
    group: www-data
    mode: 0750
  with_items: "{{ virtual_hosts }}"

- name: Create virtual hosts
  copy:
    src: /etc/apache2/sites-available/000-default.conf
    dest: /etc/apache2/sites-available/{{ item }}.conf
    remote_src: yes
  with_items: "{{ virtual_hosts }}"
