- name: Create web directories
  file:
    path: /var/www/{{ item }}
    state: directory
    mode: 0750
  with_items: "{{ virtual_hosts }}"

- name: Create virtual hosts
  template:
    src: files/virtualhost.conf
    dest: /etc/apache2/sites-available/{{ item.key }}.conf
    owner: www-data
    group: www-data
    mode: 0664
  with_dict: "{{ virtual_hosts }}"

- name: Make .ssh directory
  file:
    path: /var/www/.ssh
    state: directory
    owner: www-data
    group: www-data
    mode: 0700

- name: Copy github ssh key to new machine
  copy:
    src: files/id_rsa
    dest: "{{ item }}"
    mode: 0600
  with_items:
    - /root/.ssh/id_rsa
    - /var/www/.ssh/id_rsa

- name: Ensure github.com is a known host (root)
  lineinfile:
    dest: /root/.ssh/known_hosts
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    regexp: "^github\\.com"

- name: Copy known_hosts to www
  copy:
    src: /root/.ssh/known_hosts
    dest: /var/www/.ssh/known_hosts
    remote_src: yes
    mode: 0600
    force: no

- name: Clone git repos
  command: "git clone -b {{ item.value.branch }} --single-branch git@github.com:{{ github_owner }}/{{ item.value.repo }}.git public_html"
  args:
    chdir: /var/www/{{ item.key }}/
  with_dict: "{{ virtual_hosts }}"

- name: Move .git file
  command: "mv .git/ ../git/"
  args:
    chdir: /var/www/{{ item }}/public_html/
  with_items: "{{ virtual_hosts }}"

- name: Make .git
  lineinfile:
    dest: /var/www/{{ item }}/public_html/.git
    create: yes
    state: present
    line: "gitdir: ../git/"
  with_items: "{{ virtual_hosts }}"

- name: Create virtual hosts
  template:
    src: scripts/git_deploy.php
    dest: /var/www/{{ item }}/public_html/git_deploy.php
  with_items: "{{ virtual_hosts }}"

- name: Create post-merge file
  template:
    src: files/post-merge
    dest: /var/www/{{ item.key }}/git/hooks/post-merge
    mode: 0770
  with_dict: "{{ virtual_hosts }}"

- name: Install dependencies
  composer:
    command: install
    working_dir: /var/www/{{ item.key }}/public_html
  ignore_errors: yes
  with_dict: "{{ virtual_hosts }}"

- name: Change ownership of all new files
  file:
    path: /var/www/
    owner: www-data
    group: www-data
    recurse: yes

- name: a2ensite
  command: a2ensite {{ item }}
  with_items: "{{ virtual_hosts }}"
  notify:
  - restart apache2

- name: Let's Encrypt domains
  command: certbot --apache --non-interactive --redirect --agree-tos --email {{ admin_email }} -d {{ ssl_domains }}
