- name: Add repos
  apt_repository:
    repo: 'ppa:certbot/certbot'

- name: Install updates
  apt: upgrade=dist update_cache=yes

- name: Install essential packages
  apt: pkg="{{ item }}" state=latest
  with_items:
    - apache2
    - php
    - sqlite3
    - ntp
    - fail2ban
    - software-properties-common
    - glances
    - git
    - python-certbot-apache
    - php-curl
    - php-http
    - zip
    - unzip
    - ruby-full
    - build-essential
    - zlib1g-dev

- name: Ensure services are running and enabled
  service: name="{{ item }}" state=started enabled=yes
  with_items:
    - ntp
    - fail2ban
    - apache2

- name: Install do-agent
  shell: curl -sSL https://agent.digitalocean.com/install.sh | sh

- name: Install composer
  script: scripts/composer_installer.sh
  register: composer_install_fail

- assert:
    that: composer_install_fail != 1
    msg: "Installer must come back with 0"

- name: Add gem to bashrc part 1
  shell: echo '# Install Ruby Gems to ~/gems' >> ~/.bashrc
- name: Add gem to bashrc part 2
  shell: echo 'export GEM_HOME="$HOME/gems"' >> ~/.bashrc
- name: Add gem to bashrc part 3
  shell: echo 'export PATH="$HOME/gems/bin:$PATH"' >> ~/.bashrc
#- name: Add gem to bashrc part 4
#  shell: source ~/.bashrc

- name: Install jekyll bundler
  shell: gem install jekyll bundler

- name: Add motd
  template:
    src: files/60-camp-motd
    dest: /etc/update-motd.d/60-camp-motd
    mode: 0755