- name: Add repos
  apt_repository:
    repo: 'ppa:certbot/certbot'

- name: Install updates
  apt: upgrade=dist update_cache=yes

- name: Install essential packages
  apt: pkg="{{ item }}" state=latest
  with_items:
    - ntp
    - fail2ban
    - software-properties-common
    - glances
    - git
    - python-certbot-apache
    - php-curl
    - zip
    - unzip

- name: Ensure services are running and enabled
  service: name="{{ item }}" state=started enabled=yes
  with_items:
    - ntp
    - fail2ban
    - apache2

- name: Install composer
  script: scripts/composer_installer.sh
  register: composer_install_fail

- assert:
    that: composer_install_fail != 1
    msg: "Installer must come back with 0"
