#!/bin/sh
#
# Simple Slack Message Builder
# for post-merge
#

SERVER_NAME="{{ do_name }}"
GITHUB_OWNERNAME="{{ github_owner }}"
GITHUB_REPONAME="{{ item.value.repo }}"
BRANCH="{{ item.value.branch }}"
SLACK_HOOK="{{ slack_hook }}"
SLACK_CHANNEL="{{ slack_channel }}"
SLACK_USER="{{ slack_user }}"

GITHUB_URL="https://github.com"

HASH=$(git log -1 --pretty=%H)
AUTHOR=$(git log -1 --pretty=%an)
MESSAGE=$(git log -1 --pretty=%s)

sed -i 's%http://127.0.0.1:4000%{{ item.value.url }}%g' _config.yml
jekyll build -s . -d ../public_html

SLACK_TEXT="An update has been pushed to $GITHUB_REPONAME : \`$BRANCH\` <$GITHUB_URL/$GITHUB_OWNERNAME/$GITHUB_REPONAME/commit/$HASH|Click here> for details!"

SLACK_ATTACHMENTS="
[
  {
    \"fallback\": \"An update has been pushed to a Unami Lodge resource.\",
    \"color\": \"#36a64f\",
    \"author_name\": \"$AUTHOR\",
    \"title\": \"$GITHUB_REPONAME : $BRANCH\",
    \"title_link\": \"$GITHUB_URL/$GITHUB_OWNERNAME/$GITHUB_REPONAME/commit/$HASH\",
    \"text\": \"$MESSAGE\",
    \"footer\": \"Sent by $SERVER_NAME\"
  }
]
"

SLACK_DATA="payload={\"channel\": \"#$SLACK_CHANNEL\", \"username\": \"$SLACK_USER\", \"text\": \"$SLACK_TEXT\", \"attachments\": $SLACK_ATTACHMENTS}"

curl -X POST --data-urlencode "$SLACK_DATA" $SLACK_HOOK
